development:
  adapter: postgresql
  encoding: utf8
  database: chapteradmin_development
  username: postgres
  password: whyme461
  host: localhost


test:
  adapter: postgresql
  encoding: utf8
  database: chapteradmin_test
  username: postgres
  password: whyme461
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: chapteradmin
  username: postgres
  password: whyme461
  host: localhost
